@startuml

start 
 :Подготовка заказа; 
 :Прием товара; 
 :Аудит товара; 
 :Выдача товара;
stop

start 
 :Прием товара на реализацию; 
 :Учет месторасположения товара; 
 :Аудит работы сотрудников;
stop
 
start 
 :Продажа; 
 :Оформление покупки; 
 :Касса; 
stop

@enduml