@startuml
class Склад {
    -товары
    +принятьТовар(товар: Товар, количество)
    +аудитТовара(): void
    +выдатьТовар(товар: Товар, количество)
}

class Товар {
    -наименование
    -цена
    -количество
    +установитьНаименование(наименование)
    +установитьЦену(цена)
    +установитьКоличество(количество)
    +получитьНаименование()
    +получитьЦену()
    +получитьКоличество()
}

class ТорговоеПомещение {
    -расположение
    -товары
    +принятьТовар(товар: Товар, количество)
    +аудитРаботыСотрудников()
    +переместитьТовар(товар: Товар, количество, новоеРасположение)
}

class Работник {
    -имя
    -товары
    +взятьТовар(товар: Товар, количество)
    +справитьсяСТоварами()
}

class Касса {
    -продажи
    +зарегистрироватьПродажу(товар: Товар)
}

Склад <-- Товар
ТорговоеПомещение <-- Товар
ТорговоеПомещение <-- Работник
Товар <-- Работник
Товар <-- Касса
@enduml